baseurl = "/"
languageCode = "en-gb"
theme = "hello-2bytes"
paginate = 20

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3
  # Show reading time in minutes for posts
  showReadingTime = false

[languages]
  [languages.en]
    title = "2bytes"
    subtitle = "just my 2bytes"
    keywords = "raspberry pi, linux, security, electronics, soldering, docker, golang"
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "read on"
    readOtherPosts = "read other posts"
    newerPosts = "newer posts"
    olderPosts = "older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
     path = "/images/favicon.png"
     logoText = "2bytes"
     alt = "just my 2bytes"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About Me"
        url = "/about"
